In [8]:
import pandas as pd
import os
import glob
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

In [9]:
df=pd.read_csv('mse.csv')
df

    RP   MSE1  RMSE1   MSE2  RMSE2   MSE3   RMSE3
0    1  0.087  0.295  0.018  0.135  0.009  0.0960
1    2  0.080  0.283  0.015  0.121  0.009  0.0930
2    3  0.052  0.228  0.047  0.216  0.020  0.1400
3    4  0.397  0.630  0.070  0.264  0.035  0.1870
4    5  0.501  0.708  0.198  0.445  0.102  0.3200
5    6  0.202  0.450  0.028  0.167  0.010  0.0990
6    7  0.917  0.958  0.772  0.879  0.131  0.3620
7    8  0.412  0.642  0.078  0.280  0.033  0.1810
8    9  0.241  0.491  0.077  0.277  0.033  0.1820
9   10  0.298  0.546  0.087  0.295  0.045  0.2130
10  11  0.745  0.863  0.718  0.847  0.178  0.4220
11  12  0.087  0.295  0.069  0.262  0.021  0.1440
12  13  0.279  0.529  0.032  0.178  0.014  0.1190
13  14  0.172  0.415  0.028  0.168  0.012  0.1110
14  15  0.561  0.749  0.023  0.151  0.007  0.0840
15  16  0.169  0.411  0.020  0.141  0.009  0.0970
16  17  0.054  0.232  0.021  0.145  0.080  0.0890
17  18  0.100  0.316  0.093  0.305  0.024  0.1560
18  19  0.037  0.193  0.037  0.191  0.018  0.1330
19  20  0.059  0.242  0.049  0.222  0.017  0.1310
20  21  0.165  0.406  0.092  0.303  0.016  0.1250
21  22  0.184  0.428  0.040  0.199  0.012  0.1080
22  23  0.017  0.129  0.013  0.112  0.008  0.0890
23  24  0.081  0.284  0.009  0.097  0.005  0.0074
24  25  0.273  0.522  0.252  0.502  0.087  0.2950

In [10]:
print(np.mean(df.MSE1))

print(np.mean(df.RMSE1))

0.2468
0.44980000000000003

In [11]:
print(np.mean(df.MSE2))

print(np.mean(df.RMSE2))

0.11544
0.27608

In [13]:
print(np.mean(df.MSE3))
print(np.mean(df.RMSE3))

0.0374
0.15933600000000003